# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rule.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'rule.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrule.proto\x12\x04rule\"^\n\tFiveTuple\x12\x0e\n\x06src_ip\x18\x01 \x01(\r\x12\x0e\n\x06\x64st_ip\x18\x02 \x01(\r\x12\x10\n\x08src_port\x18\x03 \x01(\r\x12\x10\n\x08\x64st_port\x18\x04 \x01(\r\x12\r\n\x05proto\x18\x05 \x01(\r\"$\n\x03Lpm\x12\x11\n\tprefixlen\x18\x01 \x01(\r\x12\n\n\x02ip\x18\x02 \x01(\r\"\xb5\x01\n\x0bRuleRequest\x12\x1c\n\x04type\x18\x01 \x01(\x0e\x32\x0e.rule.RuleType\x12 \n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\x10.rule.RuleAction\x12\x0c\n\x02ip\x18\x03 \x01(\rH\x00\x12\x19\n\x04\x63idr\x18\x04 \x01(\x0b\x32\t.rule.LpmH\x00\x12\x0e\n\x04port\x18\x05 \x01(\rH\x00\x12 \n\x05tuple\x18\x06 \x01(\x0b\x32\x0f.rule.FiveTupleH\x00\x42\x0b\n\trule_data\"4\n\x10RuleBatchRequest\x12 \n\x05rules\x18\x01 \x03(\x0b\x32\x11.rule.RuleRequest\"0\n\x0cRuleResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\x0fRuleListRequest\x12\x1c\n\x04type\x18\x01 \x01(\x0e\x32\x0e.rule.RuleType\"4\n\x10RuleListResponse\x12 \n\x05rules\x18\x01 \x03(\x0b\x32\x11.rule.RuleRequest*F\n\x08RuleType\x12\x0b\n\x07RULE_IP\x10\x00\x12\r\n\tRULE_CIDR\x10\x01\x12\r\n\tRULE_PORT\x10\x02\x12\x0f\n\x0bRULE_5TUPLE\x10\x03*0\n\nRuleAction\x12\x0f\n\x0b\x41\x43TION_DROP\x10\x00\x12\x11\n\rACTION_ACCEPT\x10\x01\x32\xab\x02\n\x0bRuleService\x12\x30\n\x07\x41\x64\x64Rule\x12\x11.rule.RuleRequest\x1a\x12.rule.RuleResponse\x12\x33\n\nDeleteRule\x12\x11.rule.RuleRequest\x1a\x12.rule.RuleResponse\x12:\n\x0c\x41\x64\x64RuleBatch\x12\x16.rule.RuleBatchRequest\x1a\x12.rule.RuleResponse\x12=\n\x0f\x44\x65leteRuleBatch\x12\x16.rule.RuleBatchRequest\x1a\x12.rule.RuleResponse\x12:\n\tListRules\x12\x15.rule.RuleListRequest\x1a\x16.rule.RuleListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rule_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RULETYPE']._serialized_start=545
  _globals['_RULETYPE']._serialized_end=615
  _globals['_RULEACTION']._serialized_start=617
  _globals['_RULEACTION']._serialized_end=665
  _globals['_FIVETUPLE']._serialized_start=20
  _globals['_FIVETUPLE']._serialized_end=114
  _globals['_LPM']._serialized_start=116
  _globals['_LPM']._serialized_end=152
  _globals['_RULEREQUEST']._serialized_start=155
  _globals['_RULEREQUEST']._serialized_end=336
  _globals['_RULEBATCHREQUEST']._serialized_start=338
  _globals['_RULEBATCHREQUEST']._serialized_end=390
  _globals['_RULERESPONSE']._serialized_start=392
  _globals['_RULERESPONSE']._serialized_end=440
  _globals['_RULELISTREQUEST']._serialized_start=442
  _globals['_RULELISTREQUEST']._serialized_end=489
  _globals['_RULELISTRESPONSE']._serialized_start=491
  _globals['_RULELISTRESPONSE']._serialized_end=543
  _globals['_RULESERVICE']._serialized_start=668
  _globals['_RULESERVICE']._serialized_end=967
# @@protoc_insertion_point(module_scope)
